name: socialv
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common packages
  nb_utils: ^5.0.6
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.2
  permission_handler: ^6.1.1


  # Media
  date_time_picker: ^2.1.0
  image_picker: ^0.8.6
  file_picker: ^4.6.1
  just_audio: ^0.9.32
  syncfusion_flutter_pdfviewer: ^20.4.38
  photo_view: ^0.14.0
  appinio_video_player: ^1.2.0
  giphy_get: ^3.3.1
  video_player: ^2.6.1
  youtube_player_flutter: ^8.1.2

  # APIs
  http: ^0.13.4
  intl: ^0.17.0
  html: ^0.15.0

  flutter_html: ^2.2.1
  google_mobile_ads: ^2.4.0

  # State Management Technique
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5

  # Share
  share_plus: ^4.0.10
  flutter_custom_tabs: ^1.0.4

  # Firebase
  firebase_crashlytics: ^3.0.1
  cloud_firestore: ^4.0.2
  firebase_core: 2.1.0
  firebase_auth: 4.0.1
  firebase_messaging: 14.0.1


  # AUTHENTICATION
  google_sign_in: ^6.0.2
  the_apple_sign_in: ^1.1.1

  # Remote Notification
  onesignal_flutter: 3.4.1

  # Story
  story_time: ^1.0.6
  numberpicker: ^2.1.1

  lottie: ^2.3.1

  flutter_localizations:
    sdk: flutter
  dropdown_search: ^5.0.6
  slide_digital_clock: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs


dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  syncfusion_flutter_pdf: 20.4.44


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flag/
    - assets/icons/
    - assets/lottie/


